{% set name = "cryptlib" %}
{% set version = "3.4.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cryptlib-release.s3-ap-southeast-1.amazonaws.com/{{ name }}{{ version | replace(".", "") }}.zip
  sha256: e3f617ea55b1c2c6ea1a27ccc7c8dd4972d3428dfbb0c8ba52a3e4a3ea98ada6
  patches:
    - 0001-Add-missing-include.patch
    - 0002-Use-cf-compiler.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('cryptlib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    # Required for sys/auxv.h
    - sysroot_linux-64 2.17  # [linux64]
    - make
    - sed
  host:
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libcl.{{ version.split(".")[:2] | join(".") }}.dylib  # [osx]
    - test -f $PREFIX/lib/libcl.so  # [not osx]

about:
  home: https://www.cs.auckland.ac.nz/~pgut001/cryptlib/
  license: Sleepycat
  license_file: COPYING
  summary: "A high-level security interface toolkit providing encryption and authentication"

extra:
  recipe-maintainers:
    - chrisburr
